# Makefile based on BSD's pmake.
# Our mk stubs also work with GNU make.
# Copyright 2008 Roy Marples <roy@marples.name>

PROG=		dhcpcd
SRCS=		arp.c client.c common.c configure.c dhcp.c dhcpcd.c duid.c \
		info.c if.c ipv4ll.c logger.c signal.c \
		${SRC_IF} ${SRC_SOCKET}
MAN=		dhcpcd.8

VERSION=	3.2.3
CLEANFILES=	version.h dhcpcd.8

BINDIR=		${PREFIX}/sbin

# Work out how to restart services 
_RC_SH=		if test -n "${HAVE_INIT}"; then \
		test "${HAVE_INIT}" = "no" || echo "-DENABLE_${HAVE_INIT}"; \
		elif test -x /sbin/runscript; then echo "-DENABLE_OPENRC"; \
		elif test -x /sbin/service; then echo "-DENABLE_SERVICE"; \
		elif test -x /etc/rc.d/rc.S -a -x /etc/rc.d/rc.M; then echo "-DENABLE_SLACKRC"; \
		elif test -d /etc/rc.d; then echo "-DENABLE_BSDRC"; \
		elif test -d /etc/init.d; then echo "-DENABLE_SYSV"; \
		fi
_RC!=		${_RC_SH}
CFLAGS+=	${_RC}$(shell ${_RC_SH})

.SUFFIXES:	.in

MK=		mk
include ${MK}/prog.mk

CFLAGS+=	-DINFODIR=\"${INFODIR}\"
LDADD+=		${LIBRESOLV} ${LIBRT}

# As version.h is generated by us, hardcode the depend correctly.
${SRCS}:	version.h
version.h:
	echo "#define VERSION \"${VERSION}\""> version.h

.in:
	${SED} 's:@PREFIX@:${PREFIX}:g; s:@INFODIR@:${INFODIR}:g' $< > $@
