name: Clang Format Checker
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        # This is pinned to clang-format v19
      - uses: RafikFarhad/clang-format-github-action@v5
        with:
          sources: "src/**/*.h,src/**/*.c"
